config/routes.rb
Failcascade::Application.routes.draw do
  root to: 'landing#index'

  get '/about', to: 'landing#about', as: :about

  resources :alliances, only: [:index, :show], constraints: { id: /.*/ } do
    get :top_list, on: :collection
    get :growing, on: :collection
    get :collapsing, on: :collection
    get :landlords, on: :collection
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      failcascade
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.no-icons.min.css", "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css", "application", media: "all"
    = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js", "//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js", "application"
    = csrf_meta_tags
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
  %body
    %nav.navbar.navbar-default
      .container
        .navbar-header
          %button.navbar-toggle{ type: 'button', data: { toggle: 'collapse', target: '.navbar-collapse' } }
            %span.sr-only
              Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to '/', class: 'navbar-brand' do
            failcascade
            %i.icon-sort-by-attributes-alt

        .collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            %li{ class: action_name == 'top_list' ? 'active' : nil }
              = link_to top_list_alliances_path do
                %i.icon-group
                Top 10 alliances
            %li{ class: action_name == 'growing' ? 'active' : nil }
              = link_to growing_alliances_path do
                %i.icon-rocket
                Fastest growers
            %li{ class: action_name == 'collapsing' ? 'active' : nil }
              = link_to collapsing_alliances_path do
                %i.icon-calendar
                Next collapses

    .container
      = yield
    .footer
      by
      = link_to 'Slvrsmth', 'https://gate.eveonline.com/Profile/Slvrsmth/', target: '_blank'
      %small
        = link_to 'about this site', about_path

    - if Rails.env.production?
      :javascript
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-43331308-1']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();